spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin123@cluster0.equsj.mongodb.net/blog?retryWrites=true&w=majority

server:
  port: 9292

springdoc:
  api-docs:
    groups:
      enabled: true
    path: /swagger-doc/v3/api-docs
  swagger-ui:
    path: /swagger-doc/swagger-ui.html
